name: Checking
on: push

jobs:
   myjob:
     runs-on: 'ubuntu-latest'
     environment: Dev
     steps:
        - name: Echo text
          run: echo '${{ secrets.Name }}'

   myjob1:
      runs-on: 'ubuntu-latest'
      environment: Prod
      steps:
         - name: Echo text
           run: echo '${{ secrets.Name }}'
      
   
   
 
