name: Installing Python

on: push

jobs:
  build:
    strategy:
      matrix:
        py-version: 
            - 3.7 
            - 3.8 
            - 3.9
        os: 
            - ubuntu-latest 
            - macos-latest 
            - windows-latest
    runs-on: '${{ matrix.os }}'
    steps:
     - name: Set up Python
       uses: actions/setup-python@v4
       with:
         python-version: '${{ matrix.py-version }}'
        
