name: Installing Python

on: push

jobs:
  example_matrix:
    strategy:
      matrix:
        py-version: [3.7, 3.8, 3.9]
        os: [ubuntu-latest, macos-latest, windows-latest]

  build:
    runs-on: '${{ matrix.os }}'
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ matrix.py-version }}'
        
